import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Footer, Navbar } from './components'
import AuthProvider from '@/context/AuthProvider'
import Sidebar from './components/Sidebar'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/options'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  console.log(session?.user);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <AuthProvider>
            <Navbar />
            <div className='flex'>
              {session && session.user ? <Sidebar /> : null}
              <main>{children}</main>
            </div>
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
